apiVersion: v1
kind: ConfigMap

metadata:
  name: fluent-bit-config
  namespace: nodeapp

data:
  fluent-bit.conf: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log

    [OUTPUT]
        Name stdout
        Match *
